export const menu = [
  {
    category: "Greasy's Burgers",
    foodList: [
      {
        title: 'The Burnout',
        url: 'https://rs-menus-api.roocdn.com/images/985e91cc-0a14-414a-a6ba-19a06a1d843c/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'The best comeback since Britney Spears 💁‍♀️ Fried chicken, smokey bacon, aged cheddar, burnout sauce, lettuce, tomato, onion, pickles ...',
        price: '$26.00',
        ingredients: [
          ['Change to Gluten Free Bun', 2.6],
          ['Sweet Potato Chips with Burger', 2.3],
          ['Add Beef Patty', 4.7],
          ['Add Southern Fried Chicken', 4.7],
        ],
      },
      {
        title: 'Double Deluxe',
        url: 'https://rs-menus-api.roocdn.com/images/d18edb68-6482-4df1-b4dd-28151abb0398/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'Double beef, double cheese, bacon, gm relish, onion, pickles, greasy’s sauce. Served with chips. (Gf if you add the bun).',
        price: '$26.00',
        ingredients: [
          ['Sweet Potato Chips with Burger', 2.3],
          ['Add Beef Patty', 4.7],
          ['Add Southern Fried Chicken', 4.7],
        ],
      },
      {
        title: 'Greasy',
        url: 'https://rs-menus-api.roocdn.com/images/b49a49f3-ac39-494b-b835-52668e2b7ffc/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'Beef patty, lettuce, cheese, onion, pickles, gm relish, greasy’s sauce. Served with chips. (Gf if you add the bun).',
        price: '$21.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
      {
        title: 'Dirty Bird',
        url: 'https://rs-menus-api.roocdn.com/images/89e4da19-1e98-48cc-a43b-706d7524d290/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp',
        desc: 'Southern fried chicken, lettuce, tomato, onion, cheese, greasy’s sauce. Served with chips.',
        price: '$25.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
      {
        title: 'Nimbin',
        url: 'https://rs-menus-api.roocdn.com/images/8e62d227-4234-4187-8814-cb9aa8511883/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp',
        desc: 'Crumbed portobello mushroom, lettuce, tomato, onion, cheese, greasy’s sauce. Served with chips.',
        price: '$24.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
      {
        title: 'Full Service',
        url: 'https://rs-menus-api.roocdn.com/images/985e91cc-0a14-414a-a6ba-19a06a1d843c/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'The best comeback since Britney Spears 💁‍♀️ Fried chicken, smokey bacon, aged cheddar, burnout sauce, lettuce, tomato, onion, pickles ...',
        price: '$26.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
      {
        title: 'PittStop',
        url: 'https://rs-menus-api.roocdn.com/images/985e91cc-0a14-414a-a6ba-19a06a1d843c/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'The best comeback since Britney Spears 💁‍♀️ Fried chicken, smokey bacon, aged cheddar, burnout sauce, lettuce, tomato, onion, pickles ...',
        price: '$26.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
      {
        title: 'The Parmy',
        url: 'https://rs-menus-api.roocdn.com/images/985e91cc-0a14-414a-a6ba-19a06a1d843c/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'The best comeback since Britney Spears 💁‍♀️ Fried chicken, smokey bacon, aged cheddar, burnout sauce, lettuce, tomato, onion, pickles ...',
        price: '$26.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
    ],
  },
  {
    category: 'Detroit Pizza',
    foodList: [
      {
        title: 'SpitfirePizza',
        url: 'https://rs-menus-api.roocdn.com/images/985e91cc-0a14-414a-a6ba-19a06a1d843c/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'The best comeback since Britney Spears 💁‍♀️ Fried chicken, smokey bacon, aged cheddar, burnout sauce, lettuce, tomato, onion, pickles ...',
        price: '$26.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
      {
        title: 'Motor City Pizza',
        url: 'https://rs-menus-api.roocdn.com/images/985e91cc-0a14-414a-a6ba-19a06a1d843c/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'The best comeback since Britney Spears 💁‍♀️ Fried chicken, smokey bacon, aged cheddar, burnout sauce, lettuce, tomato, onion, pickles ...',
        price: '$26.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
      {
        title: 'Supreme Pizza',
        url: 'https://rs-menus-api.roocdn.com/images/985e91cc-0a14-414a-a6ba-19a06a1d843c/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'The best comeback since Britney Spears 💁‍♀️ Fried chicken, smokey bacon, aged cheddar, burnout sauce, lettuce, tomato, onion, pickles ...',
        price: '$26.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
      {
        title: 'Continental Pizza',
        url: 'https://rs-menus-api.roocdn.com/images/985e91cc-0a14-414a-a6ba-19a06a1d843c/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'The best comeback since Britney Spears 💁‍♀️ Fried chicken, smokey bacon, aged cheddar, burnout sauce, lettuce, tomato, onion, pickles ...',
        price: '$26.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
      {
        title: 'Tesla Pizza',
        url: 'https://rs-menus-api.roocdn.com/images/985e91cc-0a14-414a-a6ba-19a06a1d843c/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'The best comeback since Britney Spears 💁‍♀️ Fried chicken, smokey bacon, aged cheddar, burnout sauce, lettuce, tomato, onion, pickles ...',
        price: '$26.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
      {
        title: 'Indy 500 Pizza',
        url: 'https://rs-menus-api.roocdn.com/images/985e91cc-0a14-414a-a6ba-19a06a1d843c/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'The best comeback since Britney Spears 💁‍♀️ Fried chicken, smokey bacon, aged cheddar, burnout sauce, lettuce, tomato, onion, pickles ...',
        price: '$26.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
      {
        title: 'Meatlover Pizza',
        url: 'https://rs-menus-api.roocdn.com/images/985e91cc-0a14-414a-a6ba-19a06a1d843c/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'The best comeback since Britney Spears 💁‍♀️ Fried chicken, smokey bacon, aged cheddar, burnout sauce, lettuce, tomato, onion, pickles ...',
        price: '$26.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
      {
        title: 'Garlic Prawn',
        url: 'https://rs-menus-api.roocdn.com/images/985e91cc-0a14-414a-a6ba-19a06a1d843c/image.jpeg?width=122.5&amp;height=122.5&amp;auto=webp&amp;format=jpg&amp',
        desc: 'The best comeback since Britney Spears 💁‍♀️ Fried chicken, smokey bacon, aged cheddar, burnout sauce, lettuce, tomato, onion, pickles ...',
        price: '$26.00',
        ingredients: [
          ['Change to Gluten Free Bun', '2.65'],
          ['Sweet Potato Chips with Burger', '2.30'],
          ['Add Beef Patty', '4.70'],
          ['Add Southern Fried Chicken', '4.70'],
        ],
      },
    ],
  },
];
